### ISSUE TITLE
[warning] Also caches sessions by default

### ISSUE THREAD

**Issue by demon326** [kevinohashi/WordPressVPS#2]
Hi,

i was bored an was testing some things with Nginx and microcache on a local setup, i found your tutorial very usefull, but when i used it with a forum, the other browser(visitor) would see my session, since i was logged in and the page got cached(with this including the session).

I then found the following tutorial and now i can cache dynamic pages, but sessions are not cached:
https://thelastcicada.com/blog/2014/04/13/microcaching-with-nginx-for-wordpress/

This way you don't have any strange problems :)

Another tip is maybe to put all the Microcache logic, except the one in nginx.conf in a seperate file, for example: 'cache.conf' and then just use 'include /etc/nginx/cache.conf;' in your php logic. Keeps your Vhost clean

**Comment by kevinohashi** [comment]
I've updated the config to bypass cache for logged in users and admin stuff now. thanks!
