### ISSUE TITLE
Kindly Update to the latest One..

### ISSUE THREAD

**Issue by mkvtvseries** [kevinohashi/WordPressVPS#5]
Seem Found Nowhere New..

**Comment by kevinohashi** [comment]
what?

**Comment by mkvtvseries** [comment]
> what?

My Mistake.. Not saying fully..

WordPress VPS Installtion guide with latest testing
https://reviewsignal.com/blog/2014/06/25/40-million-hits-a-day-on-wordpress-using-a-10-vps/

Or Is the Same Procedure mentioned on your site, Still Working ?

Kinda New.. Saw ur post But on checking the date of Post it's old.. so I'm asking if there will be new One Latest Testing.

**Comment by kevinohashi** [comment]
It's old. I would recommend going with something newer. EasyEngine, ServerPilot, RunCloud, so many options out there to get stuff running on your own hardware

**Comment by mkvtvseries** [comment]
> It's old. I would recommend going with something newer. EasyEngine, ServerPilot, RunCloud, so many options out there to get stuff running on your own hardware

Thank you for the Reference
